export const allfragrances = [
        {
          id:1,
          title:'UNTAMMED SPIRIT',
          price:1500,
          discounted: 1200,
          image:'/Images/Mens Fragrances/perfume 1.webp',
          imagehover:'/Images/Mens Fragrances/perfume 1 hover.webp',
          category:'Mens Fragrances',
          qty:0,
          productcode:'#7643',
        },
        {
          id:2,
          title:'BLUE SOUL',
          price: 1500,
          discounted: 1425,
          image:'/Images/Mens Fragrances/perfume 2.webp',
          imagehover:'/Images/Mens Fragrances/perfume 2 hover.webp',
          category:'Mens Fragrances',
          qty:0,
          productcode:'#2353'
        },
        {
          id:3,
          title:'YOUNGER DAYS',
          price: 1500,
          discounted: 1150,
          image:'/Images/Mens Fragrances/perfume 3.webp',
          imagehover:'/Images/Mens Fragrances/perfume 3 hover.webp',
          category:'Mens Fragrances',
          qty:0,
          productcode:'#9234'
        },
        {
          id:4,
          title:'SILENCIO',
          price: 1500,
          discounted: 1370,
          image:'/Images/Mens Fragrances/perfume 4.webp',
          imagehover:'/Images/Mens Fragrances/perfume 4 hover.webp',
          category:'Mens Fragrances',
          qty:0,
          productcode:'#5012'
        },
        {
          id:5,
          title:'GOLD SHIMMER',
          price: 1500,
          discounted: 1250,
          image:'/Images/Mens Fragrances/perfume 5.webp',
          imagehover:'/Images/Mens Fragrances/perfume 5 hover.webp',
          category:'Mens Fragrances',
          qty:0,
          productcode:'#0414'
        },
        {
          id:6,
          title:'UNTAMMED SPIRIT',
          price:1500,
          discounted: 1200,
          image:'/Images/Mens Fragrances/perfume 1.webp',
          imagehover:'/Images/Mens Fragrances/perfume 1 hover.webp',
          category:'Mens Fragrances',
          qty:0,
          productcode:'#7643',
        },
        {
            id:7,
            title:'Komal',
            price:4200,
            discounted:3600,
            image:'/Images/AllfragrancesImages/komal img.webp',
            imagehover:'/Images/AllfragrancesImages/komal hover img.webp',
            category:'Women Fragrances',
            qty:0,
            productcode:'#8950',
          },
          {
            id:8,
            title:'Marjaan',
            price:2700,
            discounted:2300,
            image:'/Images/AllfragrancesImages/marjaan-img.webp',
            imagehover:'/Images/AllfragrancesImages/marjan-hover img.webp',
            category:'Women Fragrances',
            qty:0,
            productcode:'#8760',
          },
          {
            id:9,
            title:'JANAN SPORT',
            price: 6300,
            discounted:5300,
            image:'/Images/AllfragrancesImages/janan img.webp',
            imagehover:'/Images/AllfragrancesImages/marjan-hover img.webp',
            category:'Women Fragrances',
            qty:0,
            productcode:'#8760',
          },
          {
            id:10,
            title:'OUDH QADIM',
            price:4700,
            discounted:3700,
            image:'/Images/AllfragrancesImages/Udh-img.webp',
            imagehover:'/Images/AllfragrancesImages/udh img hover.webp',
            category:'Women Fragrances',
            qty:0,
            productcode:'#6850',
          },
          {
            id:11,
            title:'BREEZ',
            price:4500,
            discounted:3375,
            image:'/Images/AllfragrancesImages/BREEZ-IMG.webp',
            imagehover:'/Images/AllfragrancesImages/BREEZ-HOVER IG.webp',
            category:'Women Fragrances',
            qty:0,
            productcode:'#5679',
          },
          {
            id:12,
            title:'BELLA Pour Femme',
            price:6500,
            discounted:4000,
            image:'/Images/AllfragrancesImages/bella_pourfemm-IMG.webp',
            imagehover:'/Images/AllfragrancesImages/bella_pourfemme-HOVER.webp',
            category:'Women Fragrances',
            qty:0,
            productcode:'#8768',
          },
          {
            id:13,
            title:'RED RANGER',
            price:2200,
            discounted:1600,
            image:"/Images/AllfragrancesImages/red_ranger_img new.webp",
            imagehover:"/Images/AllfragrancesImages/red_ranger_hover.webp",
            category:'Kids Fragrances',
            qty:0,
            productcode:'#8738',
          },
          {
            id:14,
            title:'YELLOW RANGER',
            price:2330,
            discounted:1670,
            image:'/Images/AllfragrancesImages/yellow_ranger_IMG.webp',
            imagehover:"/Images/AllfragrancesImages/yellow_ranger HOVER.webp",
            category:'Kids Fragrances',
            qty:0,
            productcode:'#8468',
          },
          {
            id:13,
            title:'RED RANGER',
            price:2200,
            discounted:1600,
            image:"/Images/AllfragrancesImages/red_ranger_img new.webp",
            imagehover:"/Images/AllfragrancesImages/red_ranger_hover.webp",
            category:'Kids Fragrances',
            qty:0,
            productcode:'#8738',
          },
  

      ]