const menswaiscoat = [
  {
    id:1,
    image:'/Images/Mens Waiscoat/image 1.webp',
    imagehover:'/Images/Mens Waiscoat/image 1 hover.webp',
    title:'GREY SUITING WAISTCOAT | JJVC-45007',
    price: 8624,
    category:'Mens Suiting WaisCoat',
    productcode:'JJVC-45007',
    color : "Grey",
    qty: 0
  },
  {
    id:2,
    image:'/Images/Mens Waiscoat/image 2.webp',
    imagehover:'/Images/Mens Waiscoat/image 2 hover.webp',
    title:'BROWN SUITING WAISTCOAT | JJVC-45017',
    price: 11496,
    category:'Mens Suiting WaisCoat',
    productcode:'JJVC-45017',
    color : "Brown",
    qty: 0,
  },
  {
    id:3,
    image:'/Images/Mens Waiscoat/image 3.webp',
    imagehover:'/Images/Mens Waiscoat/image 3 hover.webp',
    title:'BLACK Polyster WAISTCOAT | JJVC-A-45015',
    price: 9792,
    category:'Mens Polyster WaisCoat',
    productcode:'JJVC-A-45015',
    color : "Black",
    qty: 0,
  },
  {
    id:4,
    image:'/Images/Mens Waiscoat/image 4.webp',
    imagehover:'/Images/Mens Waiscoat/image 4 hover.webp',
    title:'BROWN SUITING WAISTCOAT | JJVC-48013',
    price: 8200,
    category:'Mens Suiting WaisCoat',
    productcode:'JJVC-48013',
    color : "Brown",
    qty: 0,
  },
  {
    id:5,
    image:'/Images/Mens Waiscoat/image 5.webp',
    imagehover:'/Images/Mens Waiscoat/image 5 hover.webp',
    title:'BROWN SUITING WAISTCOAT | JJVC-A-48015',
    price: 10100,
    category:'Mens Suiting WaisCoat',
    productcode:'JJVC-A-48015',
    color : "Brown",
    qty: 0,
  },
  {
    id:6,
    image:'/Images/Mens Waiscoat/image 6.webp',
    imagehover:'/Images/Mens Waiscoat/image 6 hover.webp',
    title:'BROWN BLENDED WAISTCOAT | JJVC-48022',
    price: 10392,
    category:'Mens Blended WaisCoat',
    productcode:'JJVC-48022',
    color : "Brown",
    qty: 0,
  },
  {
    id:7,
    image:'/Images/Mens Waiscoat/image 7.webp',
    imagehover:'/Images/Mens Waiscoat/image 7 hover.webp',
    title:'MAROON BLENDED WAISTCOAT | JJVC-48021',
    price:  10392,
    category:'Mens Blended WaisCoat',
    productcode:'JJVC-48021',
    color : "Maroon",
    qty: 0,
  },
  {
    id:8,
    image:'/Images/Mens Waiscoat/image 8.webp',
    imagehover:'/Images/Mens Waiscoat/image 8 hover.webp',
    title:'GREY COTTON WAISTCOAT | JJVC-48045',
    price:  8399,
    category:'Mens Cotton WaisCoat',
    productcode:'JJVC-48045',
    qty: 0,
    color: "Grey"
  },
  {
    id:9,
    image:'/Images/Mens Waiscoat/image 9.webp',
    imagehover:'/Images/Mens Waiscoat/image 9 hover.webp',
    title:'BROWN COTTON WAISTCOAT | JJVC-48043',
    price:  8392,
    category:'Mens Cotton WaisCoat',
    productcode:'JJVC-48042',
    color : "Brown",
    qty: 0,
  },
  {
    id:10,
    image:'/Images/Mens Waiscoat/image 10.webp',
    imagehover:'/Images/Mens Waiscoat/image 10 hover.webp',
    title:'GREY COTTON WAISTCOAT | JJVC-48042',
    price: 10490,
    category:'Mens Cotton WaisCoat',
    productcode:'JJVC-48042',
    color : "Grey",
    qty: 0,
  },
  {
    id:11,
    image:'/Images/Mens Waiscoat/image 5.webp',
    imagehover:'/Images/Mens Waiscoat/image 5 hover.webp',
    title:'BROWN SUITING WAISTCOAT | JJVC-A-48015',
    price: 10072,
    category:'Mens Suiting WaisCoat',
    productcode:'JJVC-A-48015',
    color : "Brown",
    qty: 0,
  },

]

export default menswaiscoat