const mensclothing =[
  {
    id:1,
    image:'/Images/Mens Images/Suit 1 Image.webp',
    imagelarge:'/Images/Mens Images/suit 1 large img.webp',
    title:'PURPLE KURTA | JJK-A-37792',
    price: 4290,
    discounted: 3890,
    color:'Purple',
    season:'Winter',
    category:'Mens Kurta',
    productcode:'JJK-A-37792',
    qty: 0,
  },
  {
    id:2,
    image:'/Images/Mens Images/Suit 2 Image.webp',
    imagelarge:'/Images/Mens Images/Suit 2 large Img.webp',
    title:'BROWN KURTA | JJK-W-37795',
    price: 3890,
    discounted: 3450,
    color:'Brown',
    season:'Winter',
    category:'Mens Kurta',
    qty: 0,
    productcode:'JJK-W-37795'
  },
  {
    id:3,
    image:'/Images/Mens Images/Suit 3 Image.webp',
    imagelarge:'/Images/Mens Images/Suit 3 large img.webp',
    title:'GREY MEN KURTA | JJK-W-32842',
    price: 3890,
    discounted: 3670,
    color:'Grey',
    season:'Winter',
    category:'Mens Kurta',
    qty: 0,
    productcode:'JJK-W-32842'
  },
  {
    id:4,
    image:'/Images/Mens Images/Suit 4 Image.webp',
    imagelarge:'/Images/Mens Images/white suit hover img.webp',
    title:'WHITE KURTA | JJK-W-47121',
    price: 7990,
    discounted: 6890,
    color:'White',
    season:'Winter',
    category:'Mens Kurta',
    qty: 0,
    productcode:'JJK-W-47121'
  },
  {
    id:5,
    image:'/Images/Mens Images/Suit 5 Image.webp',
    imagelarge:'/Images/Mens Images/blue suit hover.webp',
    title:'MEN BLUE KURTA | JJK-A-32835',
    price: 4290,
    discounted: 3890,
    color:'Blue',
    season:'Winter',
    category:'Mens Kurta',
    qty: 0,
    productcode:'JJK-A-32835'
  },
  {
    id:6,
    image:'/Images/Mens Images/Suit 1 Image.webp',
    imagelarge:'/Images/Mens Images/purple hover img.webp',
    title:'PURPLE KURTA | JJK-A-37792',
    price: 4290,
    discounted: 3890,
    color:'Purple',
    season:'Winter',
    category:'Mens Kurta',
    productcode:'JJK-A-37792',
    qty: 0,
  },
  {
    id:7,
    image:'/Images/Womens/Womens Trendy Kurti Images/image 1.webp',
    imagelarge:'/Images/Womens/Womens Trendy Kurti Images/image 1 hover.webp',
    title:'RED CAMBRIC KURTI | JJLK-W-JWS-23-3020',
    price: 2392,
    qty:0,
    category:'Kurti',
    color: "Red",
    productcode:'JJLK-W-JWS-23-3020'
  },
  {
    id:8,
    image:'/Images/Womens/Womens Trendy Kurti Images/image 2.webp',
    imagelarge:'/Images/Womens/Womens Trendy Kurti Images/image 2 hover.webp',
    title:'GREEN CAMBRIC KURTI | JJLK-W-JWS-23-3045',
    price: 3992,
    qty:0,
    category:'Kurti',
    color: "Green",
    productcode:'JJLK-W-JWS-23-3045'
  },
  {
    id:9,
    image:'/Images/Womens/Womens Trendy Kurti Images/image 3.webp',
    imagelarge:'/Images/Womens/Womens Trendy Kurti Images/image 3 hover.webp',
    title:'MUSTARD CAMBRIC KURTI | JJLK-W-JWS-23',
    price: 3992,
    qty:0,
    category:'Kurti',
    color: "Mustard",
    productcode:'JJLK-W-JWS-23-3044'
  },
  {
    id:10,
    image:'/Images/Womens/Womens Trendy Kurti Images/image 4.webp',
    imagelarge:'/Images/Womens/Womens Trendy Kurti Images/image 4 hover.webp',
    title:'BLACK CAMBRIC KURTI | JJLK-W-JWS-23-3043',
    price: 3992,
    qty:0,
    category:'Kurti',
    color: "Black",
    productcode:'JJLK-W-JWS-23-3043'
  },
  {
    id:11,
    image:'/Images/Womens/Womens Trendy Kurti Images/image 5.webp',
    imagelarge:'/Images/Womens/Womens Trendy Kurti Images/image 5 hover.webp',
    title:'WHITE CAMBRIC KURTI | JJLK-W-JWS-23-3042',
    price: 3992,
    qty:0,
    category:'Kurti',
    color: "White",
    productcode:'JJLK-W-JWS-23-3042'
  },
  {
    id:12,
    image:'/Images/Womens/Womens Trendy Kurti Images/image 2.webp',
    imagelarge:'/Images/Womens/Womens Trendy Kurti Images/image 2 hover.webp',
    title:'GREEN CAMBRIC KURTI | JJLK-W-JWS-23-3045',
    price: 3992,
    qty:0,
    color: "Green",
    category:'Kurti',
    productcode:'JJLK-W-JWS-23-3045'
  },
  {
    id:13,
    image:'/Images/Boys & Girls/Kids Boys Images/image 1.webp',
    imagelarge:'/Images/Boys & Girls/Kids Boys Images/image 1 hover.webp',
    title:'PURPLE KURTA PAJAMA | JCKP-S-37774',
    price:'3,190',
    color: "Purple",
    category:'Kids Boys',
    productcode:'JCKP-S-37774'
  },
  {
    id:14,
    image:'/Images/Boys & Girls/Kids Boys Images/image 2.webp',
    imagelarge:'/Images/Boys & Girls/Kids Boys Images/image 2 hover.webp',
    title:'BROWN BLENDED KURTA | JCK-S-38869',
    price:'2,590',
    color: "Brown",
    category:'Kids Boys',
    productcode:'JCK-S-38869'
  },
  {
    id:15,
    image:'/Images/Boys & Girls/Kids Boys Images/image 3.webp',
    imagelarge:'/Images/Boys & Girls/Kids Boys Images/image 3 hover.webp',
    title:'BLACK BLENDED KURTA | JCK-S-38890',
    price:'2,890',
    color: "Black",
    category:'Kids Boys',
    productcode:'JCK-S-38890'
  },
  {
    id:16,
    image:'/Images/Boys & Girls/Kids Boys Images/image 4.webp',
    imagelarge:'/Images/Boys & Girls/Kids Boys Images/image 4 hover.webp',
    title:'GREEN COTTON KURTA | JCK-S-38887',
    price:'2,890',
    color: "Green",
    category:'Kids Boys',
    productcode:'JCK-S-38887'
  },
  {
    id:17,
    image:'/Images/Boys & Girls/Kids Boys Images/image 5.webp',
    imagelarge:'/Images/Boys & Girls/Kids Boys Images/image 5 hover.webp',
    title:'PURPLE BLENDED KURTA | JCK-S-38880',
    color: "Purple",
    price:'2,152',
    category:'Kids Boys',
    productcode:'JCK-S-38880'
  },
  {
    id:18,
    image:'/Images/Boys & Girls/Kids Boys Images/image 6.webp',
    imagelarge:'/Images/Boys & Girls/Kids Boys Images/image 6 hover.webp',
    title:'BLUE BLENDED KURTA | JCK-S-38878',
    price:'1,752',
    color: "Blue",
    category:'Kids Boys',
    productcode:'JCK-S-38878'
  },
  {
    id:19,
    image:'/Images/New Arrivals/New Arrivals Infants/NA Infants Image 1.webp',
    title:'GREEN BLENDED KAMEEZ SHALWAR | JJIKS-S-38882',
    price: 1992,
    qty:0,
    color: "Green",
    category:'New Arrivals Infants',
    productcode:'JJIKS-S-38882'
  },
  {
    id:20,
    image:'/Images/New Arrivals/New Arrivals Infants/NA Infants Image 2.webp',
    title:'BLUE COTTON KAMEEZ SHALWAR | JJIKS-S-34404',
    price: 2490,
    qty:0,
    color: "Blue",
    category:'New Arrivals Infants',
    productcode:'JJIKS-S-34404'
  },
  {
    id:21,
    image:'/Images/New Arrivals/New Arrivals Infants/NA Infants Image 3.webp',
    title:'BLUE BLENDED KAMEEZ SHALWAR | JJIKS-A-35841-R7',
    price: 2190,
    qty:0,
    color: "Blue",
    category:'New Arrivals Infants',
    productcode:'JJIKS-A-35841-R7'
  },
  {
    id:22,
    image:'Images/New Arrivals/New Arrivals Infants/NA Infants Image 4.webp',
    title:'BLACK BLENDED KAMEEZ SHALWAR | JJIKS-A-35840-R7',
    price: 2190,
    qty:0,
    color: "Black",
    category:'New Arrivals Infants',
    productcode:'JJIKS-A-35840-R7'
  },
  {
    id:23,
    image:'/Images/New Arrivals/New Arrivals Infants/NA Infants Image 5.webp',
    title:'BLACK BLENDED KAMEEZ SHALWAR | JJIKS-A-35836-R7',
    price: 2190,
    qty:0,
    color: "Black",
    category:'New Arrivals Infants',
    productcode:'JJIKS-A-35836-R7'
  },
  {
    id:28,
    image:'/Images/Boys & Girls/Kids Girls Images/image 1.webp',
    imagehover:'/Images/Boys & Girls/Kids Girls Images/image 1 hover.webp',
    title:'BLUE POLY-COTTON GIRLS 3PC | JGK-W-JWK-23-5006',
    price:'4,552',
    category:'Kids Girls',
    productcode:'JGK-W-JWK-23-5006',
    qty:0,
    color : "Blue"

  },
  {
    id:29,
    image:'/Images/Boys & Girls/Kids Girls Images/image 2.webp',
    imagehover:'/Images/Boys & Girls/Kids Girls Images/image 2 hover.webp',
    title:'RED POLY-COTTON GIRLS 3PC | JGK-W-JWK-23-5004',
    price:'4,552',
    category:'Kids Girls',
    productcode:'JGK-W-JWK-23-5004',
    qty:0,
    color : "Red"
  },
  {
    id:30,
    image:'/Images/Boys & Girls/Kids Girls Images/image 3.webp',
    imagehover:'/Images/Boys & Girls/Kids Girls Images/image 3 hover.webp',
    title:'PURPLE POLY-COTTON GIRLS 3PC | JGK-W-JWK-23',
    price:'4,552',
    category:'Kids Girls',
    qty:0,
    productcode:'JGK-W-JWK-23-5005',
    color : "Purple"
  },
  {
    id:31,
    image:'/Images/Boys & Girls/Kids Girls Images/image 4.webp',
    imagehover:'/Images/Boys & Girls/Kids Girls Images/image 4 hover.webp',
    title:'GREEN SILK LAWN GIRLS 3PC | JGK-W-23-1929',
    price: 7352,
    category:'Kids Girls',
    qty:0,
    productcode:'JGK-W-23-1929',
    color : "Green"
  },

]

export default mensclothing