const newarrivalapi = [
  {
    id:1,
    image:'/Images/Mens Waiscoat/image 1.webp',
    imagehover:'/Images/Mens Waiscoat/image 1 hover.webp',
    title:'GREY SUITING WAISTCOAT | JJVC-45007',
    price:'8,624',
    category:'Mens WaisCoat',
    productcode:'JJVC-45007',
    color:'Grey',
  },
  {
    id:2,
    image:'/Images/Mens Waiscoat/image 2.webp',
    imagehover:'/Images/Mens Waiscoat/image 2 hover.webp',
    title:'BROWN SUITING WAISTCOAT | JJVC-45017',
    price:'11,496',
    category:'Mens WaisCoat',
    productcode:'JJVC-45017',
    color:'Brown',
  },
  {
    id:3,
    image:'/Images/Kameez Shalwar Images/Image 1.webp',
    imagehover:'/Images/Kameez Shalwar Images/Image 1 hover.webp',
    price:'5,030',
    title:'BLACK BLENDED KAMEEZ SHALWAR | JJKS-A-30779-R27-AP',
    category:'Mens Kameez Shalwar',
    productcode:'JJKS-A-30779-R27-AP',
  },
  {
    id:4,
    image:'/Images/Womens/Womens Trendy Kurti Images/image 8.webp',
    imagehover:'/Images/Womens/Womens Trendy Kurti Images/image 8 hover.webp',
    title:'MULTICOLOR KHADDAR KURTI | JJLK-W-JWS-23-3032',
    price:'3,890',
    productcode:'JJLK-W-JWS-23-3032',
    category:'Kurti',
    color:'Multi',
  },
  {
    id:5,
    image:'/Images/Mens Waiscoat/image 4.webp',
    imagehover:'/Images/Mens Waiscoat/image 4 hover.webp',
    title:'BROWN SUITING WAISTCOAT | JJVC-48013',
    price:' 8,208',
    category:'Mens WaisCoat',
    productcode:'JJVC-48013',
    color:'Brown',
  },
  {
    id:6,
    image:'/Images/Womens/Womens Trendy Kurti Images/image 10.webp',
    imagehover:'/Images/Womens/Womens Trendy Kurti Images/image 10 hover.webp',
    title:'PINK KHADDAR KURTI | JJLK-W-JWS-23-3033',
    price:'3,192',
    productcode:'JJLK-W-JWS-23-3033',
    category:'Kurti',
    color:'Pink',
  },
  {
    id:7,
    image:'/Images/Womens/Womens Trendy Kurti Images/image 1.webp',
    imagehover:'/Images/Womens/Womens Trendy Kurti Images/image 1 hover.webp',
    title:'RED CAMBRIC KURTI | JJLK-W-JWS-23-3020',
    price:'2,392',
    productcode:'JJLK-W-JWS-23-3020',
    category:'Kurti',
    color:'Red',
  },
  {
    id:8,
    image:'/Images/Kameez Shalwar Images/Image 4.webp',
    imagehover:'/Images/Kameez Shalwar Images/Image 4.webp',
    price:'5,584',
    title:'GREEN BLENDED KAMEEZ SHALWAR | JJKS-43288',
    category:'Mens Kameez Shalwar',
    productcode:'JJKS-43288',
  },
  {
    id:9,
    image:'/Images/Mens Waiscoat/image 7.webp',
    imagehover:'/Images/Mens Waiscoat/image 7 hover.webp',
    title:'MAROON BLENDED WAISTCOAT | JJVC-48021',
    price:' 10,392',
    category:'Mens WaisCoat',
    productcode:'JJVC-48021',
    color:'Maroon',
  },
  {
    id:10,
    image:'/Images/Mens Waiscoat/image 8.webp',
    imagehover:'/Images/Mens Waiscoat/image 8 hover.webp',
    title:'GREY WAISTCOAT | JJVC-48045',
    price:' 8,392',
    category:'Mens WaisCoat',
    productcode:'JJVC-48045',
    color:'Grey',
  },
  {
    id:11,
    image:'/Images/Womens/Womens Trendy Kurti Images/image 4.webp',
    imagehover:'/Images/Womens/Womens Trendy Kurti Images/image 4 hover.webp',
    title:'BLACK CAMBRIC KURTI | JJLK-W-JWS-23-3043',
    price:'3,992',
    productcode:'JJLK-W-JWS-23-3043',
    category:'Kurti',
    color:'Black',
  },
  {
    id:12,
    image:'/Images/Mens Waiscoat/image 10.webp',
    imagehover:'/Images/Mens Waiscoat/image 10 hover.webp',
    title:'GREY WAISTCOAT | JJVC-48042',
    price:' 10,490',
    category:'Mens WaisCoat',
    productcode:'JJVC-48042',
    color:'Grey',
  },
  {
    id:13,
    image:'/Images/Womens/Womens Trendy Kurti Images/image 6.webp',
    imagehover:'/Images/Womens/Womens Trendy Kurti Images/image 6 hover.webp',
    title:'MULTICOLOR KHADDAR KURTI | JJLK-W-JWS-23-3030',
    price:'3,112',
    category:'Kurti',
    productcode:'JJLK-W-JWS-23-3030',
    color:'Multi',
  },
  {
    id:14,
    image:'/Images/Kameez Shalwar Images/Image 9.webp',
    imagehover:'/Images/Kameez Shalwar Images/Image 9 hover.webp',
    price:'4,990',
    title:'BROWN BLENDED KAMEEZ SHALWAR | JJKS-A-47005-R3-AP',
    category:'Mens Kameez Shalwar',
    productcode:'JJKS-A-47005-R3-AP',
  },
  {
    id:15,
    image:'/Images/Womens/Womens Trendy Kurti Images/image 7.webp',
    imagehover:'/Images/Womens/Womens Trendy Kurti Images/image 7 hover.webp',
    title:'BLUE KHADDAR KURTI | JJLK-W-JWS-23-3031',
    price:'3,992',
    productcode:'JJLK-W-JWS-23-3031',
    category:'Kurti',
    color:'Blue',
  },
  {
    id:16,
    image:'/Images/Mens Waiscoat/image 3.webp',
    imagehover:'/Images/Mens Waiscoat/image 3 hover.webp',
    title:'BLACK WAISTCOAT | JJVC-A-45015',
    price:' 9,792',
    category:'Mens WaisCoat',
    productcode:'JJVC-A-45015',
    color:'Black',
  },
  {
    id:17,
    image:'/Images/Womens/Womens Trendy Kurti Images/image 9.webp',
    imagehover:'/Images/Womens/Womens Trendy Kurti Images/image 9 hover.webp',
    title:'BLUE KHADDAR KURTI | JJLK-W-JWS-23-3028',
    price:'3,112',
    productcode:'JJLK-W-JWS-23-3028',
    category:'Kurti',
    color:'Blue',
  },
  {
    id:18,
    image:'/Images/Mens Waiscoat/image 5.webp',
    imagehover:'/Images/Mens Waiscoat/image 5 hover.webp',
    title:'BROWN SUITING WAISTCOAT | JJVC-A-48015',
    price:' 10,072',
    category:'Mens WaisCoat',
    productcode:'JJVC-A-48015',
    color:'Brown',
  },
  {
    id:19,
    image:'/Images/Mens Waiscoat/image 6.webp',
    imagehover:'/Images/Mens Waiscoat/image 6 hover.webp',
    title:'BROWN BLENDED WAISTCOAT | JJVC-48022',
    price:' 10,392',
    category:'Mens WaisCoat',
    productcode:'JJVC-48022',
    color:'Brown',
  },
  {
    id:20,
    image:'/Images/Womens/Womens Trendy Kurti Images/image 2.webp',
    imagehover:'/Images/Womens/Womens Trendy Kurti Images/image 2 hover.webp',
    title:'GREEN CAMBRIC KURTI | JJLK-W-JWS-23-3045',
    price:'3,992',
    productcode:'JJLK-W-JWS-23-3045',
    category:'Kurti',
    color:'Green',
  },
  {
    id:21,
    image:'/Images/Womens/Womens Trendy Kurti Images/image 3.webp',
    imagehover:'/Images/Womens/Womens Trendy Kurti Images/image 3 hover.webp',
    title:'MUSTARD CAMBRIC KURTI | JJLK-W-JWS-23-3044',
    price:'3,992',
    productcode:'JJLK-W-JWS-23-3044',
    category:'Kurti',
    color:'Mustard',
  },
  {
    id:22,
    image:'/Images/Mens Waiscoat/image 9.webp',
    imagehover:'/Images/Mens Waiscoat/image 9 hover.webp',
    title:'BROWN WAISTCOAT | JJVC-48043',
    price:' 8,392',
    category:'Mens WaisCoat',
    productcode:'',
    color:'Brown',
  },
  {
    id:23,
    image:'/Images/Kameez Shalwar Images/Image 8.webp',
    imagehover:'/Images/Kameez Shalwar Images/Image 8 hover.webp',
    price:'4,690',
    title:'GREY BLENDED KAMEEZ SHALWAR | JJKS-S-30821-R21-AP',
    category:'Mens Kameez Shalwar',
    productcode:'JJKS-S-30821-R21-AP',
  },
 
  {
    id:24,
    image:'/Images/Womens/Womens Trendy Kurti Images/image 5.webp',
    imagehover:'/Images/Womens/Womens Trendy Kurti Images/image 5 hover.webp',
    title:'WHITE CAMBRIC KURTI | JJLK-W-JWS-23-3042',
    price:'3,992',
    productcode:'JJLK-W-JWS-23-3042',
    category:'Kurti',
    color:'White',
  },
  {
    id:25,
    image:'/Images/Kameez Shalwar Images/Image 2.webp',
    imagehover:'/Images/Kameez Shalwar Images/Image 2 hover.webp',
    price:'4,872',
    title:'WHITE BLENDED KAMEEZ SHALWAR | JJKS-S-34485',
    category:'Mens Kameez Shalwar',
    productcode:'JJKS-S-34485',
  },
  {
    id:26,
    image:'/Images/Kameez Shalwar Images/Image 3.webp',
    imagehover:'/Images/Kameez Shalwar Images/Image 3 hover.webp',
    price:'5,336',
    title:'YELLOW BLENDED KAMEEZ SHALWAR | JJKS-S-32792',
    category:'Mens Kameez Shalwar',
    productcode:'JJKS-S-32792',
  },
 
  {
    id:27,
    image:'/Images/Kameez Shalwar Images/Image 5.webp',
    imagehover:'/Images/Kameez Shalwar Images/Image 5 hover.webp',
    price:'6,990',
    title:'GREEN KAMEEZ SHALWAR | JJKS-S-32819',
    category:'Mens Kameez Shalwar',
    productcode:'JJKS-S-32819',
  },
  {
    id:28,
    image:'/Images/Kameez Shalwar Images/Image 6.webp',
    imagehover:'/Images/Kameez Shalwar Images/Image 6 hover.webp',
    price:'5,592',
    title:'BLACK CVC KAMEEZ SHALWAR | JJKS-S-34482',
    category:'Mens Kameez Shalwar',
    productcode:'JJKS-S-34482',
  },
  {
    id:29,
    image:'/Images/Kameez Shalwar Images/Image 7.webp',
    imagehover:'/Images/Kameez Shalwar Images/Image 7 hover.webp',
    price:'6,790',
    title:'BROWN BLENDED KAMEEZ SHALWAR | JJKS-S-34479',
    category:'Mens Kameez Shalwar',
    productcode:'JJKS-S-34479',
  },
]

export default newarrivalapi