const stitched = [
  {
    id:1,
    title:'PINK KHADDAR 3PC STITCHED | JJPW-W-JW-23-1719',
    image:'/Images/Womens/Stitched Womens/image 1.webp',
    imagehover:'/Images/Womens/Stitched Womens/image 1 hover.webp',
    price:7192,
    category:'Women Stitched 1PC',
    productcode:'JJPW-W-JW-23-1719',
    color: "Pink",
    qty: 0
  },
  {
    id:2,
    title:'BLUE KHADDAR 3PC STITCHED | JJPW-W-JW-23-1873',
    image:'/Images/Womens/Stitched Womens/image 2.webp',
    imagehover:'/Images/Womens/Stitched Womens/image 2 hover.webp',
    price:5592,
    category:'Women Stitched 1PC',
    productcode:'JJPW-W-JW-23-1873',
    color: "Blue",
    qty: 0,
  },
  {
    id:3,
    title:'RED KHADDAR 3PC STITCHED | JJPW-W-JW-23-1872',
    image:'/Images/Womens/Stitched Womens/image 3.webp',
    imagehover:'/Images/Womens/Stitched Womens/image 3 hover.webp',
    price:5432,
    category:'Women Stitched 2PC',
    productcode:'JJPW-W-JW-23-1872',
    color: "Red",
    qty: 0,
  },
  {
    id:4,
    title:'BROWN PALACHI 3PC STITCHED | JJPW-W-JW-23-1755',
    image:'/Images/Womens/Stitched Womens/image 4.webp',
    imagehover:'/Images/Womens/Stitched Womens/image 4 hover.webp',
    price:9592,
    category:'Women Stitched 2PC',
    productcode:'JJPW-W-JW-23-1755',
    color: "Brown",
    qty: 0,
  },
  {
    id:5,
    title:'MULTICOLOR PALACHI 3PC STITCHED | JJPW-W-JW-23-1753',
    image:'/Images/Womens/Stitched Womens/image 5.webp',
    imagehover:'/Images/Womens/Stitched Womens/image 5 hover.webp',
    price:9592,
    category:'Women Stitched 2PC',
    productcode:'JJPW-W-JW-23-1753',
    color: "Multicolor",
    qty: 0
  },
  {
    id:6,
    title:'GREEN KHADDAR 3PC STITCHED | JJPW-W-JW-23-1718',
    image:'/Images/Womens/Stitched Womens/image 6.webp',
    imagehover:'/Images/Womens/Stitched Womens/image 6 hover.webp',
    price:7192,
    category:'Women Stitched 2PC',
    productcode:'JJPW-W-JW-23-1718',
    color: "Green",
    qty: 0,
  },
  {
    id:7,
    title:'BLACK KHADDAR 3PC STITCHED | JJPW-W-JW-23-1717',
    image:'/Images/Womens/Stitched Womens/image 7.webp',
    imagehover:'/Images/Womens/Stitched Womens/image 7 hover.webp',
    price:7192,
    category:'Women Stitched 3PC',
    productcode:'JJPW-W-JW-23-1717',
    color: "Black",
    qty: 0,
  },
  {
    id:8,
    title:'MAROON VELVET 3PC STITCHED | JJPW-W-JPS-23-3946',
    image:'/Images/Womens/Stitched Womens/image 8.webp',
    imagehover:'/Images/Womens/Stitched Womens/image 8 hover.webp',
    price:15992,
    category:'Women Stitched 1PC',
    productcode:'JJPW-W-JPS-23-3946',
    color: "Maroon",
    qty: 0,
  },
  {
    id:9,
    title:'VIOLET VELVET 3PC STITCHED | JJPW-W-JPS-23-3944',
    image:'/Images/Womens/Stitched Womens/image 9.webp',
    imagehover:'/Images/Womens/Stitched Womens/image 9 hover.webp',
    price:19432,
    category:'Women Stitched 1PC',
    productcode:'JJPW-W-JPS-23-3944',
    color: "Voilet",
    qty: 0,
  },
  {
    id:10,
    title:'RED KHADDAR 3PC STITCHED | JJPW-W-JW-23-1872',
    image:'/Images/Womens/Stitched Womens/image 3.webp',
    imagehover:'/Images/Womens/Stitched Womens/image 3 hover.webp',
    price:5432,
    category:'Women Stitched 3PC',
    productcode:'JJPW-W-JW-23-1872',
    color: "Red",
    qty: 0,
  },
  {
    id:11,
    title:'BROWN PALACHI 3PC STITCHED | JJPW-W-JW-23-1755',
    image:'/Images/Womens/Stitched Womens/image 4.webp',
    imagehover:'/Images/Womens/Stitched Womens/image 4 hover.webp',
    price:9592,
    category:'Women Stitched 3PC',
    productcode:'JJPW-W-JW-23-1755',
    qty: 0,
    color: "Brown",

  },
  {
    id:7,
    title:'BLACK KHADDAR 3PC STITCHED | JJPW-W-JW-23-1717',
    image:'/Images/Womens/Stitched Womens/image 7.webp',
    imagehover:'/Images/Womens/Stitched Womens/image 7 hover.webp',
    price:7192,
    category:'Women Stitched 3PC',
    productcode:'JJPW-W-JW-23-1717',
    color: "Black",
    qty: 0,
  },
]

export default stitched